enum StoryFilterPreset {
  original,
  mono,
  sepia,
  warm,
  cool,
  fade,
  contrast,
}

const List<StoryFilterPreset> storyFilterPresets = [
  StoryFilterPreset.original,
  StoryFilterPreset.mono,
  StoryFilterPreset.sepia,
  StoryFilterPreset.warm,
  StoryFilterPreset.cool,
  StoryFilterPreset.fade,
  StoryFilterPreset.contrast,
];

const List<double> storyFilterIdentityMatrix = [
  1,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
];

List<double> storyFilterPresetMatrix(StoryFilterPreset preset) {
  return switch (preset) {
    StoryFilterPreset.original => storyFilterIdentityMatrix,
    StoryFilterPreset.mono => const [
        0.2126,
        0.7152,
        0.0722,
        0,
        0,
        0.2126,
        0.7152,
        0.0722,
        0,
        0,
        0.2126,
        0.7152,
        0.0722,
        0,
        0,
        0,
        0,
        0,
        1,
        0,
      ],
    StoryFilterPreset.sepia => const [
        0.393,
        0.769,
        0.189,
        0,
        0,
        0.349,
        0.686,
        0.168,
        0,
        0,
        0.272,
        0.534,
        0.131,
        0,
        0,
        0,
        0,
        0,
        1,
        0,
      ],
    StoryFilterPreset.warm => const [
        1.06,
        0,
        0,
        0,
        8,
        0,
        1.02,
        0,
        0,
        2,
        0,
        0,
        0.92,
        0,
        -4,
        0,
        0,
        0,
        1,
        0,
      ],
    StoryFilterPreset.cool => const [
        0.92,
        0,
        0,
        0,
        -3,
        0,
        1,
        0,
        0,
        0,
        0,
        0,
        1.1,
        0,
        6,
        0,
        0,
        0,
        1,
        0,
      ],
    StoryFilterPreset.fade => const [
        0.86,
        0,
        0,
        0,
        18,
        0,
        0.86,
        0,
        0,
        18,
        0,
        0,
        0.86,
        0,
        18,
        0,
        0,
        0,
        1,
        0,
      ],
    StoryFilterPreset.contrast => const [
        1.22,
        0,
        0,
        0,
        -28,
        0,
        1.22,
        0,
        0,
        -28,
        0,
        0,
        1.22,
        0,
        -28,
        0,
        0,
        0,
        1,
        0,
      ],
  };
}

List<double> storyFilterMatrix(
  StoryFilterPreset preset, {
  double intensity = 1,
}) {
  final clampedIntensity = intensity.clamp(0.0, 1.0).toDouble();
  if (preset == StoryFilterPreset.original || clampedIntensity == 0) {
    return storyFilterIdentityMatrix;
  }

  final target = storyFilterPresetMatrix(preset);
  return List<double>.generate(
    storyFilterIdentityMatrix.length,
    (index) {
      final start = storyFilterIdentityMatrix[index];
      return start + (target[index] - start) * clampedIntensity;
    },
    growable: false,
  );
}

bool storyFilterIsActive(StoryFilterPreset preset, double intensity) {
  return preset != StoryFilterPreset.original && intensity.clamp(0.0, 1.0) > 0;
}
